config:
  docker_registry: tonybarr16
  access_key: "Aws_access_key"
  secret_key: "AWS_secret_key"
  bucket: 2024-02-ic4302-gr1
  producer:
    replicas: 1
    name: s3-crawler
    image: s3-crawler
  consumer:
    replicas: 1
    name: ingest
    image: ingest
  huggingfaceApi:
    name: huggingfaceapi
    replicas: 1
    image: huggingface-api
